### ISSUE TITLE
External data when no External card

### ISSUE THREAD

**Issue by Gitoffthelawn** [MajeurAndroid/Applications-Info#3]
Fantastic App.  Thank you!

It lists "External" data (and states that apps are using "External" data) even when phone has no External storage Card.

Is "External" the best term for the UI?  What does "External" mean?

**Comment by MajeurAndroid** [comment]
Hi, thanks.
An Android phone bas storage for apps, where you cannot write, and a
storage for user where you can put your songs for example and where your
apps are moved when you click move in settings. In addition to that there
is ext sd card. So in fact external storage just means user storage not
relally "external", but external to the system. there is a confusion
because in old android version (<2.3) the only user was an sd card, now
phones have an embedded user storage so sd card is not needed like before.

Le mercredi 29 avril 2015, Gitoffthelawn <notifications@github.com> a
écrit :
> Fantastic App. Thank you!
>
> It lists "External" data (and states that apps are using "External" data)
even when phone has no External storage Card.
>
> Is "External" the best term for the UI? What does "External" mean?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/ejvDDIuHww6D97sgyM-GXd1Aq9XntVH7JYB06psHoDmjET1Jdt9u6W2kwdteDqFlzF8XSB_8k_GdtPTzttKM5JmAm0i1AqtcbC_9NXzCg1hs_Xn2kpQOTwxN-ybZ6U0edictl-emnVWqFAgPJiKI4IfegwVPhw=s0-d-e1-ft#https://github.com/notifications/beacon/AKz7CBjODtMyhl5xdoasDa7RZd__WcbAks5oETx4gaJpZM4EL-Ub.gif
>

**Comment by Gitoffthelawn** [comment]
Thanks!  Are the values listed under "External" in Applications Info inclusive of both types of external storage (external to the system and sd card)?  Does Applications Info differentiate between External (meaning "external to the system") and External (meaning "sd card")?

**Comment by MajeurAndroid** [comment]
External include both external storages

**Comment by Gitoffthelawn** [comment]
Thanks.  What are your thoughts of separating those two types of storage for devices that have both?

**Comment by MajeurAndroid** [comment]
It's not possible, retrieve application detailed size isn't possible officially in android SDK. Here I use AIDL interface and java reflection to retrieve it but it is not officially supported by android SDK.
This result in java object that contains only size that you can see in applications info app, I can't do better.
